CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    type VARCHAR2(20) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    gender VARCHAR2(10),
    phone_number VARCHAR2(20),
    company_name VARCHAR2(100),
    crn VARCHAR2(50),
    director_name VARCHAR2(100),
    telephone VARCHAR2(20)
);

CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    account_no VARCHAR2(20) UNIQUE NOT NULL,
    type VARCHAR2(20) NOT NULL,
    balance NUMBER(12,2) NOT NULL,
    company_name VARCHAR2(100),
    company_address VARCHAR2(200),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE transactions (
    transaction_id VARCHAR2(50) PRIMARY KEY,
    account_id NUMBER,
    transaction_date DATE,
    type VARCHAR2(20),
    amount NUMBER(12,2),
    reference VARCHAR2(100),
    balance NUMBER(12,2),
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);
Select * From transactions;
Select * From customers;

